# Generated by Django 5.1.2 on 2026-07-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_clinic_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('diagnostic', 'Diagnostic Center')], default='clinic', max_length=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
