# Generated by Django 5.1.2 on 2026-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_clinic_clinic_type_clinic_established_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('clinic_admin', 'Clinic Admin'), ('system_admin', 'System Admin')], default='individual', max_length=20),
        ),
    ]
