# Generated by Django 5.1.2 on 2026-07-31 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_userprofile_employee_id_userprofile_is_active_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='patientdata',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='main_page.clinic'),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='country_code',
            field=models.CharField(blank=True, default='IN', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='lifestyle',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise 3-5 days/week)'), ('active', 'Very active (hard exercise 6-7 days/week)'), ('super_active', 'Super active (very hard exercise/physical job)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='pid',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
