# Generated by Django 5.1.2 on 2026-08-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_patientdata_options_patientdata_clinic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_text', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(blank=True, max_length=50)),
                ('risk_percentage', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('clinical_priority', models.CharField(blank=True, max_length=50)),
                ('status', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('follow_up', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_days', models.IntegerField(blank=True, null=True)),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('generated_on', models.DateTimeField()),
                ('generated_at', models.CharField(blank=True, max_length=100)),
                ('processing_time', models.CharField(blank=True, max_length=50)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main_page.predictiondata')),
            ],
            options={
                'db_table': 'prediction_results',
                'ordering': ['-generated_on'],
            },
        ),
    ]
